/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharma;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logTF = new javax.swing.JTextField();
        pwdTF = new javax.swing.JPasswordField();
        conbut = new javax.swing.JButton();
        lbl_user = new javax.swing.JLabel();
        lbl_pwd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        logTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logTFActionPerformed(evt);
            }
        });

        pwdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdTFActionPerformed(evt);
            }
        });

        conbut.setText("S'authentifier");
        conbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conbutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(conbut))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logTF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwdTF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_user)
                            .addComponent(lbl_pwd))))
                .addContainerGap(383, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(logTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_user)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pwdTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_pwd)
                .addGap(21, 21, 21)
                .addComponent(conbut)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logTFActionPerformed

    private void pwdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdTFActionPerformed

    private void conbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conbutActionPerformed
        // TODO add your handling code here:
        if(logTF.getText().trim().isEmpty() && pwdTF.getText().trim().isEmpty()){
            lbl_user.setText("Username is Empty");
            lbl_pwd.setText("Password is Empty");
        }
        else if(logTF.getText().trim().isEmpty()){
            lbl_user.setText("Username is Empty");
        }
        else if(pwdTF.getText().trim().isEmpty()){
            lbl_pwd.setText("Password is Empty");
        }
        else {
            String username = "root";
            String password = "passer";
            String url = "jdbc:mysql://localhost/pharmacie";

            try
            {
                //connexion base
                Class.forName("com.mysql.jdbc.Driver");
                Connection connexion = DriverManager.getConnection(url,username,password);
                //Statement instruction = connexion.createStatement();
                //ResultSet resultat = instruction.executeQuery("SELECT *  FROM UTILISATEUR where login=? and pwd=?" );
                String sql = "SELECT *  FROM Utilisateur where login=? and mdp=?";
                PreparedStatement pst = connexion.prepareStatement(sql);
                pst.setString(1, logTF.getText());
                pst.setString(2, pwdTF.getText());
                ResultSet rs = pst.executeQuery();
                if(rs.next()){
                    //JOptionPane.showMessageDialog(null,"Username and Password Matched");
                    //int id = 0;
                    String type = rs.getString("Type");
                    if(null != type) switch (type) {
                        case "Admin":
                        MenuAdmin menu = new MenuAdmin();
                        menu.setVisible(true);
                        setVisible(false);
                        break;
                        case "Gerant":
                        MenuGerant menu2 = new MenuGerant();
                        menu2.setVisible(true);
                        setVisible(false);
                        break;
                        case "Employe":
                        MenuEmp menu1 = new MenuEmp();
                        menu1.setVisible(true);
                        setVisible(false);
                        break;
                        default:
                        System.out.println("erreur");
                        break;
                    }
                }

                else{
                    JOptionPane.showMessageDialog(null,"Username and Password do not Matched");
                    logTF.setText("");
                    pwdTF.setText("");

                }
            }
            catch (ClassNotFoundException | SQLException | HeadlessException e)
            {
                System.out.println("echec pilote : "+e);
            }
        }

    }//GEN-LAST:event_conbutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conbut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_pwd;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JTextField logTF;
    private javax.swing.JPasswordField pwdTF;
    // End of variables declaration//GEN-END:variables
}
