/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharma;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form User
     */
    DefaultTableModel dtm = new DefaultTableModel();
    public User() {
        initComponents();
        dtm.addColumn("Id");
        dtm.addColumn("Nom");
        dtm.addColumn("Prenom");
        dtm.addColumn("Email");
        dtm.addColumn("Login");
        dtm.addColumn("Mot de passe");
        dtm.addColumn("Telephone");
        dtm.addColumn("Type");
        
        String username = "root";
        String password = "passer";
        String url = "jdbc:mysql://localhost/pharmacie";
        
        try {
            //connexion base
                Class.forName("com.mysql.jdbc.Driver");
                Connection connexion = DriverManager.getConnection(url,username,password);
                String sql = "SELECT *  FROM Utilisateur"; 
                PreparedStatement pst = connexion.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
            while (rs.next()){
                dtm.addRow(new Object[]{
                    rs.getObject(1),rs.getObject(2),rs.getObject(3),rs.getObject(4)
                    ,rs.getObject(5),rs.getObject(6),rs.getObject(7),rs.getObject(8)});
            }
        } catch (Exception e1) {
        }
        UserTable.setModel(dtm);
    }
    
    private void afficher(){
        String username = "root";
        String password = "passer";
        String url = "jdbc:mysql://localhost/pharmacie";
    try {
        dtm.setRowCount(0);
                Class.forName("com.mysql.jdbc.Driver");
                Connection connexion = DriverManager.getConnection(url,username,password);
                String sql = "SELECT *  FROM Utilisateur"; 
                PreparedStatement pst = connexion.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
        while(rs.next()){
        dtm.addRow(new Object[]{rs.getString("id"),rs.getString("Nom"),rs.getString("Prenom"),rs.getString("email"),
            rs.getString("login"),rs.getString("mdp"),rs.getString("telephone"),rs.getString("Type")});

        }
        }catch(Exception e){System.err.println(e);}

    UserTable.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PrenomTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        LoginTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TelTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TypeTF = new javax.swing.JTextField();
        idTF = new javax.swing.JTextField();
        MailTF = new javax.swing.JTextField();
        AjoutUser = new javax.swing.JButton();
        MdpaTF = new javax.swing.JPasswordField();
        UpdateUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DeleteUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nom");

        UserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nom", "Prenom", "Email", "Login", "Mot de passe", "Téléphone", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        UserTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                UserTableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        UserTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(UserTable);

        jLabel3.setText("Prenom");

        jLabel4.setText("Email");

        NameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTFActionPerformed(evt);
            }
        });

        jLabel5.setText("Login");

        PrenomTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrenomTFActionPerformed(evt);
            }
        });

        jLabel6.setText("Mot de passe");

        LoginTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginTFActionPerformed(evt);
            }
        });

        jLabel7.setText("Téléphone");

        TelTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelTFActionPerformed(evt);
            }
        });

        jLabel8.setText("Type");

        TypeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeTFActionPerformed(evt);
            }
        });

        idTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTFActionPerformed(evt);
            }
        });

        MailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MailTFActionPerformed(evt);
            }
        });

        AjoutUser.setText("Ajouter");
        AjoutUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutUserActionPerformed(evt);
            }
        });

        MdpaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MdpaTFActionPerformed(evt);
            }
        });

        UpdateUser.setText("Modifier");
        UpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateUserActionPerformed(evt);
            }
        });

        jLabel1.setText("Id");

        DeleteUser.setText("Supprimer");
        DeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TelTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(MdpaTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoginTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MailTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PrenomTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idTF, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TypeTF, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(174, 174, 174)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(AjoutUser)
                        .addGap(54, 54, 54)
                        .addComponent(UpdateUser)
                        .addGap(60, 60, 60)
                        .addComponent(DeleteUser)
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(PrenomTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(MailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(LoginTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(MdpaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TelTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AjoutUser)
                            .addComponent(UpdateUser)
                            .addComponent(DeleteUser))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_UserTableAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_UserTableAncestorAdded

    private void UserTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserTableMouseClicked
        // TODO add your handling code here:

        try{
            int i=UserTable.getSelectedRow();deplace(i);
        }catch(Exception e){JOptionPane.showMessageDialog(null,"erreur de deplacement "+e.getLocalizedMessage());}
    }//GEN-LAST:event_UserTableMouseClicked

    private void NameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTFActionPerformed

    private void PrenomTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrenomTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrenomTFActionPerformed

    private void LoginTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginTFActionPerformed

    private void TelTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelTFActionPerformed

    private void TypeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeTFActionPerformed

    private void idTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTFActionPerformed

    
    
    private void deplace(int i){
        
    try {
        idTF.setText(dtm.getValueAt(i,0).toString());
        NameTF.setText(dtm.getValueAt(i,1).toString());
        PrenomTF.setText(dtm.getValueAt(i,2).toString());
        MailTF.setText(dtm.getValueAt(i,3).toString());
        LoginTF.setText(dtm.getValueAt(i,4).toString());
        MdpaTF.setText(dtm.getValueAt(i,5).toString());
        TelTF.setText(dtm.getValueAt(i,6).toString());
        TypeTF.setText(dtm.getValueAt(i,7).toString());

    }catch (Exception e){System.err.println(e);
    JOptionPane.showMessageDialog(null,"erreur de deplacement"+e.getLocalizedMessage());}
    }
    
    private void MailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MailTFActionPerformed

    private void AjoutUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutUserActionPerformed
        // TODO add your handling code here:

        String username = "root";
        String password = "passer";
        String url = "jdbc:mysql://localhost/pharmacie";

        int id = new Integer(idTF.getText());
        String prenom = PrenomTF.getText();
        String nom = NameTF.getText();
        String mail = MailTF.getText();
        String login = LoginTF.getText();
        String mdp = MdpaTF.getText();
        String tel = TelTF.getText();
        String type = TypeTF.getText();

        if(idTF.getText().equals("") || NameTF.getText().equals("") || PrenomTF.getText().equals("")
            || MailTF.getText().equals("")|| LoginTF.getText().equals("")|| MdpaTF.getText().equals("")
            || TelTF.getText().equals("")|| TypeTF.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs");
        }
        else{
            if(JOptionPane.showConfirmDialog(null, "Voulez vous Ajouter?", "Confirmation",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
                try{

                    //connexion base
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection connexion = DriverManager.getConnection(url,username,password);
                    String sql = "INSERT INTO Utilisateur Values('"+id+"','"+nom+"','"+prenom+"',"
                    + "'"+mail+"','"+login+"','"+mdp+"','"+tel+"','"+type+"')";
                    PreparedStatement pst = connexion.prepareStatement(sql);
                    pst.executeUpdate();

                    JOptionPane.showMessageDialog(null,"Utilisateur ajouter avec succées");

                    afficher();
                    idTF.setText("");
                    NameTF.setText("");
                    PrenomTF.setText("");
                    MailTF.setText("");
                    LoginTF.setText("");
                    MdpaTF.setText("");
                    TelTF.setText("");
                    TypeTF.setText("");

                }
                catch (Exception e)
                {
                    System.out.println("echec pilote : "+e);
                }

            }
            else{
                JOptionPane.showMessageDialog(null, "données non enrigistrées!!!!!");
            }
        }
    }//GEN-LAST:event_AjoutUserActionPerformed

    private void MdpaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MdpaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MdpaTFActionPerformed

    private void UpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateUserActionPerformed
        // TODO add your handling code here:
        String username = "root";
        String password = "passer";
        String url = "jdbc:mysql://localhost/pharmacie";

        try {
            if (JOptionPane.showConfirmDialog (null,"confirmer la modification","modification",
                JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {

            Class.forName("com.mysql.jdbc.Driver");
            Connection connexion = DriverManager.getConnection(url,username,password);
            String sql ="UPDATE Utilisateur SET nom='"+NameTF.getText()+"',prenom='"+PrenomTF.getText()+
            "',email='"+MailTF.getText()+"',login='"+LoginTF.getText()+"',mdp='"+MdpaTF.getText()+"',telephone='"+TelTF.getText()+"',Type='"+TypeTF.getText()+"' WHERE id = " +idTF.getText();

            PreparedStatement pst = connexion.prepareStatement(sql);
            pst.executeUpdate();
            afficher();

        }
        } catch (Exception e){JOptionPane.showMessageDialog(null,"erreur de modifier !!!!!!!"+e.getMessage());
            System.err.println(e);}
    }//GEN-LAST:event_UpdateUserActionPerformed

    private void DeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteUserActionPerformed
        // TODO add your handling code here:
        String username = "root";
        String password = "passer";
        String url = "jdbc:mysql://localhost/pharmacie";

        try {
            if(JOptionPane.showConfirmDialog(null,"Attention vous avez supprimer un utilisateur,est ce que vous êtes sure?"
                ,"supprimer etudient",JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION)

        if(idTF.getText().length() != 0){
            Class.forName("com.mysql.jdbc.Driver");
            Connection connexion = DriverManager.getConnection(url,username,password);
            String sql ="Delete From Utilisateur where id = "+idTF.getText();
            PreparedStatement pst = connexion.prepareStatement(sql);
            pst.executeUpdate();
            afficher();
        }
        else { JOptionPane.showMessageDialog(null,"veuillez SVP remplir le champ id !");}

        }catch (Exception e){JOptionPane.showMessageDialog(null,"erreur de supprimer \n"+e.getMessage());}

    }//GEN-LAST:event_DeleteUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjoutUser;
    private javax.swing.JButton DeleteUser;
    private javax.swing.JTextField LoginTF;
    private javax.swing.JTextField MailTF;
    private javax.swing.JPasswordField MdpaTF;
    private javax.swing.JTextField NameTF;
    private javax.swing.JTextField PrenomTF;
    private javax.swing.JTextField TelTF;
    private javax.swing.JTextField TypeTF;
    private javax.swing.JButton UpdateUser;
    private javax.swing.JTable UserTable;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
